# version: "3.8"

networks:
  ea_erp_net:
    driver: bridge

services:
  embarque_angra_erp_ui:
    build: .
    container_name: embarque_angra_erp_ui
    volumes:
      - .:/usr/share/app
    ports:
      - 3040:3000
    restart: always
    networks:
      - ea_erp_net
    environment:
      - PASS=123456
