networks:
  # embarque_angra_erp_net:
  #   driver: bridge
  observability-net:
    external: true

services:
  embarque_angra_erp_ui:
    build: .
    container_name: embarque_angra_erp_ui
    volumes:
      - .:/usr/share/app
    ports:
      - 3045:3000
    restart: always
    networks:
      # - embarque_angra_erp_net
      - observability-net

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888" # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # http gRPC receiver
      - "55679:55679" # zpages extension
      - "9464:9464"
    depends_on:
      - jaeger
      - prometheus
    networks:
      # - embarque_angra_erp_net
      - observability-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      # - embarque_angra_erp_net
      - observability-net

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686"
      - "14268"
      - "14250"
    networks:
      # - embarque_angra_erp_net
      - observability-net
