# version: "3.8"

networks:
  embarque_angra_erp_net:
    driver: bridge

services:
  embarque_angra_erp_ui:
    build: .
    container_name: embarque_angra_erp_ui
    volumes:
      - .:/usr/share/app
    ports:
      - 3040:3000
    restart: always
    networks:
      - embarque_angra_erp_net
    environment:
      - PASS=123456

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  # ssh-agent:
  #   image: jenkins/ssh-agent
volumes:
  jenkins_home:
